/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mobilez.ui;

/**
 *
 * @author duong
 */
public class FrmGioiThieu extends javax.swing.JPanel {

    /**
     * Creates new form FrmGioiThieu
     */
    public FrmGioiThieu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        lblLogo.setBackground(new java.awt.Color(85, 159, 198));
        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mobilez/icon/Poly.png"))); // NOI18N
        lblLogo.setOpaque(true);
        add(lblLogo, java.awt.BorderLayout.PAGE_START);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(85, 159, 198));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Baloo 2 ExtraBold", 0, 30)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText("\n      Dự án 1. Mục tiêu thực hiện là Quản lý cửa hàng điện thoại\n      Được thực hiện bởi Nhóm 4 - IT16301\n      Giáo viên giám sát : Nguyễn Hoàng Tiến\n      Sinh viên thực hiện:  Tạ Văn Nam - PH13082 \n                                        Nguyễn Quốc Khánh - PH13545\n                                        Dương Văn Sơn - PH13283 \n                                        Nguyễn Quốc Tuấn - PH15433\n                                        Phạm Công Giang - PH13293");
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblLogo;
    // End of variables declaration//GEN-END:variables
}
