/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mobilez.ui;

import com.mobilez.models.QuayHang;
import com.mobilez.utils.Auth;
import com.mobilez.utils.JdbcHelper;
import java.sql.*;
import javax.swing.DefaultComboBoxModel;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author uhtku
 */
public class FrmViewQuayHang extends javax.swing.JPanel {

    /**
     * Creates new form FrmHangHoa
     */
    DefaultTableModel modelTbl;
    DefaultComboBoxModel<QuayHang> modelCbo;
    int index = -1;

    public FrmViewQuayHang() {
        initComponents();
        modelTbl = (DefaultTableModel) tblList.getModel();
        modelCbo = (DefaultComboBoxModel) cboQH.getModel();
        this.fillCbo();
        this.fillByRole();
    }

    //My method------------------------------------------------------------------------------------
    //search
    private void searchQH() {
        try {
            String sql = "select TENMH,RAM,DUNGLUONG,MAUSAC,TGBH,GIABAN,CHITIETQUAYHANG.SOLUONG\n"
                    + "from CHITIETQUAYHANG join MATHANG on CHITIETQUAYHANG.MAMH=MATHANG.MAMH\n"
                    + "where MAQH like ? and TRANGTHAI = 1 and TENMH like ?";
            QuayHang qh = (QuayHang) cboQH.getSelectedItem();
            String search = "%"+txtSearch.getText()+"%";
            ResultSet rs = JdbcHelper.query(sql, qh.getMaQH(),search);
            modelTbl.setRowCount(0);
            while (rs.next()) {
                String giaBan = rs.getString("GIABAN");
                int vt = giaBan.indexOf(".");
                giaBan = giaBan.substring(0, vt);
                modelTbl.addRow(new Object[]{
                    rs.getString("TENMH"),
                    rs.getString("RAM") + "GB",
                    rs.getString("DUNGLUONG") + "GB",
                    rs.getString("MAUSAC"),
                    rs.getInt("TGBH") + " Tháng",
                    giaBan,
                    rs.getInt("SOLUONG")
                });
            }
        } catch (Exception e) {
        }
    }

    //Role
    private void fillByRole() {
            for (int i = 0; i < cboQH.getItemCount(); i++) {
                cboQH.setSelectedIndex(i);
                QuayHang qh = (QuayHang) cboQH.getSelectedItem();
                if (Auth.maQuay.equalsIgnoreCase(qh.getMaQH())) {
                    cboQH.setSelectedIndex(i);
                    
                    break;
                }
            }
            if (!Auth.isManager()) {
            cboQH.setEnabled(false);
        }
    }

    //fill cbo
    private void fillCbo() {
        try {
            String sql = "select * from QUAYHANG";
            ResultSet rs = JdbcHelper.query(sql);
            while (rs.next()) {
                QuayHang qh = new QuayHang(rs.getString(1), rs.getString(2), rs.getBoolean(3));
                modelCbo.addElement(qh);
            }
            rs.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    //fill table
    private void fillTable() {
        try {
            String sql = "select TENMH,RAM,DUNGLUONG,MAUSAC,TGBH,GIABAN,CHITIETQUAYHANG.SOLUONG\n"
                    + "from CHITIETQUAYHANG join MATHANG on CHITIETQUAYHANG.MAMH=MATHANG.MAMH\n"
                    + "where MAQH like ?  and TRANGTHAI = 1";
            QuayHang qh = (QuayHang) cboQH.getSelectedItem();
            ResultSet rs = JdbcHelper.query(sql, qh.getMaQH());
            modelTbl.setRowCount(0);
            while (rs.next()) {
                String giaBan = rs.getString("GIABAN");
                int vt = giaBan.indexOf(".");
                giaBan = giaBan.substring(0, vt);
                modelTbl.addRow(new Object[]{
                    rs.getString("TENMH"),
                    rs.getString("RAM") + "GB",
                    rs.getString("DUNGLUONG") + "GB",
                    rs.getString("MAUSAC"),
                    rs.getInt("TGBH") + " Tháng",
                    giaBan,
                    rs.getInt("SOLUONG")
                });
            }
        } catch (Exception e) {
        }
    }

//------------------------------------------------------------------------------------------------------------//
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpStatus = new javax.swing.ButtonGroup();
        cboQH = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblList = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(34, 116, 173));

        cboQH.setBackground(new java.awt.Color(34, 116, 173));
        cboQH.setForeground(new java.awt.Color(255, 255, 255));
        cboQH.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboQHItemStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Baloo 2 ExtraBold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DANH SÁCH MẶT HÀNG TẠI QUẦY");

        tblList.setBackground(new java.awt.Color(34, 116, 173));
        tblList.setFont(new java.awt.Font("Baloo 2", 0, 13)); // NOI18N
        tblList.setForeground(new java.awt.Color(255, 255, 255));
        tblList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên mặt hàng", "RAM", "Dung lợng", "Màu sắc", "Thời gian BH", "Giá bán", "Số lượng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblList.setToolTipText("");
        tblList.setGridColor(new java.awt.Color(255, 255, 255));
        tblList.setRowHeight(25);
        tblList.setSelectionBackground(new java.awt.Color(51, 51, 51));
        tblList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblList.setShowGrid(true);
        tblList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblList);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mobilez/icon/search_32px.png"))); // NOI18N

        txtSearch.setBackground(new java.awt.Color(34, 116, 173));
        txtSearch.setForeground(new java.awt.Color(255, 255, 255));
        txtSearch.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mobilez/icon/shop_32px.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(660, 660, 660)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cboQH, 0, 183, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboQH)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cboQH, jLabel3, jLabel4, txtSearch});

    }// </editor-fold>//GEN-END:initComponents

    private void tblListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            index = tblList.getSelectedRow();
        }


    }//GEN-LAST:event_tblListMouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        this.searchQH();
    }//GEN-LAST:event_txtSearchKeyReleased

    private void cboQHItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboQHItemStateChanged
        // TODO add your handling code here:
        this.fillTable();
    }//GEN-LAST:event_cboQHItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboQH;
    private javax.swing.ButtonGroup grpStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblList;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
